version: '3.3'
services:
    sync:
        container_name: resilio
        ports:
            - '0.0.0.0:8888:8888'
            - 55555
        volumes:
            - '/home/abraxas/docker/resilio/data:/mnt/sync'
            - '/home/abraxas:/mnt/mounted_folders/home/abraxas'
        restart: on-failure
        image: resilio/sync
